version: '3'

services:
  web:
    build: .
    environment:
      - EDITOR=vim
    volumes:
      - .:/app/
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=gamble_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5342

  datadog:
    image: gcr.io/datadoghq/agent:latest
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_SITE=datadoghq.com
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  postgres:
